# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := feature_extract
ARDUINO_LIBS := BioData Plaquette "CSV Parser"
#ARDUINO_LIB_DIRS := ../libraries
EXTRA_CXXFLAGS := -fexceptions
include ../libraries/EpoxyDuino/EpoxyDuino.mk
